title: The Good Game Factory
email: your-email@example.com
logo: assets/logo.png
description: >- # this means to ignore newlines until "baseurl:"
  The website for Mr Figs and other works by The Good Game Factory
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: thegoodgamefactory
github_username: thegoodgamefactory
remote_theme: pages-themes/minimal@v0.2.0

github:
  repository: https://github.com/thegoodgamefactory/

plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one

